### ISSUE TITLE
Support for Conga 6090 Ultra

### ISSUE THREAD

**Issue by aictur** [congatudo/stuff#3]
Hi, I recently bought a Conga 6090 Ultra and tried to install valetudo (despite not being on the tested list).
I can access the app but I can't really use the robot itself, I assume because of this error:
```
[2022-01-23T13:52:24.424Z] [WARN] Error while calling BasicControlCapability Action home Error: There is no robot connected to server
    at CecotecBasicControlCapability.home (/snapshot/Valetudo/backend/lib/robots/cecotec/capabilities/CecotecBasicControlCapability.js:33:19)
    at home (/snapshot/Valetudo/backend/lib/webserver/capabilityRouters/BasicControlCapabilityRouter.js:19:40)
    at /snapshot/Valetudo/backend/lib/webserver/capabilityRouters/BasicControlCapabilityRouter.js:29:31
    at Layer.handle [as handle_request] (/snapshot/Valetudo/node_modules/express/lib/router/layer.js:95:5)
    at next (/snapshot/Valetudo/node_modules/express/lib/router/route.js:137:13)
    at Route.dispatch (/snapshot/Valetudo/node_modules/express/lib/router/route.js:112:3)
    at Layer.handle [as handle_request] (/snapshot/Valetudo/node_modules/express/lib/router/layer.js:95:5)
    at /snapshot/Valetudo/node_modules/express/lib/router/index.js:281:22
    at Function.process_params (/snapshot/Valetudo/node_modules/express/lib/router/index.js:335:12)
    at next (/snapshot/Valetudo/node_modules/express/lib/router/index.js:275:10)
    at Function.handle (/snapshot/Valetudo/node_modules/express/lib/router/index.js:174:3)
    at router (/snapshot/Valetudo/node_modules/express/lib/router/index.js:47:12)
    at Layer.handle [as handle_request] (/snapshot/Valetudo/node_modules/express/lib/router/layer.js:95:5)
    at trim_prefix (/snapshot/Valetudo/node_modules/express/lib/router/index.js:317:13)
    at /snapshot/Valetudo/node_modules/express/lib/router/index.js:284:7
    at Function.process_params (/snapshot/Valetudo/node_modules/express/lib/router/index.js:335:12)
```

Is there any known limitation with this model? Can I debug this error?
Thanks.

**Comment by asdolo** [comment]
I also have a Conga 6090 Ultra. I can test whatever new version you have if you tell me how :)

**Comment by txitxo0** [comment]
You can go through there to follow the news about the new protocol
https://github.com/adrigzr/agnoc/issues/34
